apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "omero-dropbox-operator.fullname" . }}-operator
  labels:
    {{- include "omero-dropbox-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "omero-dropbox-operator.name" . }}-operator
  template:
    metadata:
      labels:
        app: {{ include "omero-dropbox-operator.name" . }}-operator
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "omero-dropbox-operator.serviceAccountName" . }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MODE
              value: "OPERATOR"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
