apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "omero-dropbox-operator.fullname" . }}-webhook
  labels:
    {{- include "omero-dropbox-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "omero-dropbox-operator.name" . }}-webhook
  template:
    metadata:
      labels:
        app: {{ include "omero-dropbox-operator.name" . }}-webhook
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ omero-dropbox-operator.webhookServiceAccountName }}
      containers:
        - name: webhook
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MODE
              value: "WEBHOOK"
            - name: GUNICORN_WORKERS
              value: "{{ .Values.webhook.env.GUNICORN_WORKERS }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "omero-dropbox-operator.fullname" . }}-webhook
  labels:
    {{- include "omero-dropbox-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "omero-dropbox-operator.name" . }}-webhook

{{- if .Values.webhook.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "omero-dropbox-operator.webhookServiceAccountName" . }}
  annotations:
{{ toYaml .Values.webhook.serviceAccount.annotations | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: omero-dropbox-system
  name: omero-dropbox-webhook-role
rules:
- apiGroups: ["","omero.lavlab.edu"]
  resources: ["configmaps", "omerodropboxes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["", "batch"]
  resources: ["pods", "jobs"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: omero-dropbox-webhook-rolebinding
  namespace: omero-dropbox-system
subjects:
- kind: ServiceAccount
  name: {{ include "omero-dropbox-operator.webhookServiceAccountName" . }}
  namespace: omero-dropbox-system
roleRef:
  kind: Role
  name: omero-dropbox-webhook-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
