apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: omerodropboxes.omero.lavlab.edu
spec:
  group: omero.lavlab.edu
  names:
    kind: OmeroDropbox
    listKind: OmeroDropboxList
    plural: omerodropboxes
    singular: omerodropbox
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                watch:
                  type: object
                  properties:
                    watched:
                      type: object
                      properties:
                        pvc:
                          type: object
                          properties:
                            name:
                              type: string
                            path:
                              type: string
                    configMapName:
                      type: string
              required: [ "watch" ]
