# Default values for omero-dropbox-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: ghcr.io/lavlabinfrastructure/omero-dropbox-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Custom values for the webhook's functionality
webhookServiceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}

watch:
  env:
    EXCLUDE_PATTERN: "\\.txt$" # unfortunately need to escape the escape
  
defaultImportJob:
  config.yaml: |
    image: "ghcr.io/lavlabinfrastructure/omero-dropbox-worker:v1.0.6"
    omeroUserSecret:
      username: 
        name: 'omero-connection-secret'
        key: 'username'
      password: 
        name: 'omero-connection-secret'
        key: 'password'
      server:
        name: 'omero-connection-secret'
        key: 'server'
      port:
        name: 'omero-connection-secret'
        key: 'port'
    command:
      - bash
      - -c
      - |
        export name=${FILE##*/}; 
        export name=${name%%.*};
        export ds=${FILE%/*};
        export ds=${ds##*/};
        bioformats2raw --memo-directory=/tmp $FILE /tmp/zarr && 
        raw2ometiff --rgb --compression=JPEG --quality=100 /tmp/zarr /tmp/${name}.ome.tiff && 
        omero -u $OMERO_USERNAME -w $OMERO_PASSWORD -s $OMERO_SERVER -p $OMERO_PORT import -T Dataset:name:$ds /tmp/${name}.ome.tiff && 
        rm $FILE
    env: []
    labels: []
    annotations: []
    additionalMounts: []
    additionalVolumes: []



